2024-05-25 03:01:16 INFO Starting test suite tests.test_data_explorer
ERROR: test_data_explorer (unittest.loader._FailedTest)
ImportError: Failed to import test module: test_data_explorer
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
ModuleNotFoundError: No module named 'tests.test_data_explorer'


2024-05-25 03:01:16 INFO Test suite tests.test_data_explorer finished
